// <auto-generated />
using System;
using LocalPayment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalPayment.Migrations
{
    [DbContext(typeof(LocalPaymentContext))]
    [Migration("20220210164854_LocalPayment")]
    partial class LocalPayment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("LocalPayment.Models.Card", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("limite")
                        .HasColumnType("double");

                    b.Property<string>("nombre")
                        .HasColumnType("text");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.Property<int?>("personaid")
                        .HasColumnType("int");

                    b.Property<double>("tasa")
                        .HasColumnType("double");

                    b.Property<string>("titular")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("personaid");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("LocalPayment.Models.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("apellido")
                        .HasColumnType("text");

                    b.Property<string>("dirección")
                        .HasColumnType("text");

                    b.Property<int>("dni")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("text");

                    b.Property<string>("tarjeta")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("LocalPayment.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.Property<string>("usuario")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LocalPayment.Models.Card", b =>
                {
                    b.HasOne("LocalPayment.Models.Person", "persona")
                        .WithMany()
                        .HasForeignKey("personaid");

                    b.Navigation("persona");
                });
#pragma warning restore 612, 618
        }
    }
}
